services:
  app:
    container_name: kriptora_station_app
    build: .
    volumes:
      - .:/app
    networks:
      - kriptora-station-local-network

  # You can comment Redis container creation if you dont need Redis pubsubs as a notifier
  redis:
    container_name: kriptora_station_redis
    image: redis
    command: redis-server --requirepass root --bind 0.0.0.0
    ports:
      - 63790:6379
    networks:
      - kriptora-station-local-network
networks:
    kriptora-station-local-network:
      driver: bridge
      name: kriptora-station-local-network